//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.OrganizePlanilha.UI.Web.Dao.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MAQUINA
    {
        public int idMAQUINA { get; set; }
        public Nullable<int> idPROJETO { get; set; }
        public string xMAQUINA { get; set; }
        public string SELOS_ESQUERDO { get; set; }
        public string SELOS_DIREITO { get; set; }
        public string QTDE_TERM_ESQUERDO { get; set; }
        public string QTDE_TERM_DIREITO { get; set; }
        public string CALIBRE { get; set; }
        public string QTDE_CAPACIDADE { get; set; }
        public string QTDE_TOLERANCIA { get; set; }
        public string QTDE_YY { get; set; }
    
        public virtual TB_PROJETO TB_PROJETO { get; set; }
    }
}
