//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.OrganizePlanilha.UI.Web.Dao.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PLANILHA
    {
        public int id_PLANILHA { get; set; }
        public int idPROJETO { get; set; }
        public string PLANTA { get; set; }
        public string TIPO { get; set; }
        public string CALIBRE { get; set; }
        public string LONG_CORT { get; set; }
        public string CANTIDAD { get; set; }
        public string COD_DI { get; set; }
        public string TERM_IZQ { get; set; }
        public string COD_DD { get; set; }
        public string TERM_DER { get; set; }
        public string COD_01_I { get; set; }
        public string COD_01_D { get; set; }
        public string ACC_01_I { get; set; }
        public string ACC_01_D { get; set; }
    
        public virtual TB_PROJETO TB_PROJETO { get; set; }
    }
}
